server:
  port: 8081
  context-path: /dev
spring:
  datasource:
      primary:
                driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
                url: jdbc:sqlserver://101.200.175.157:1433;DatabaseName=MyAutosTest
                username: myautos
                password: myautos2016
            secondary:
                driver-class-name: com.mysql.jdbc.Driver
                url: jdbc:mysql://192.168.15.143:3306/wangzhengt
                username: root
                password: 123456
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true